language: node_js
node_js: 
  - "0.10"
branches:
  only:
    - master
env:
  global:
    - "REPOSITORY=visualcaptcha-npm"
  secure: "KRBDUp2mqR7y12nSUzxaExownlISzSR0O5F1AjckB+G2Yfvox0lbZMBaYKqp/YasuHM8LE7Fcm9HsnUDzZcSYI5GSfMMMCF4QdqbiQ0Y4UVpKAtNhU8BDZltmScommvjK11F9HaGck3+QodJNGoDj+lNDmhgFRHHtt5OY8QFDKU="
after_success:
  - "curl --insecure --data 'deploy={\"repository\":\"$REPOSITORY\",\"branch\":\"$TRAVIS_BRANCH\"}' https://githooks.emotionloop.com/?k=$AUTH_KEY"
